# Generated by Django 6.0 on 2025-12-06 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_board', to='api.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KanbanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('DOING', 'Doing'), ('DONE', 'Done')], db_index=True, default='TODO', max_length=10)),
                ('votes', models.IntegerField(default=0)),
                ('allow_voting', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.kanbanboard')),
            ],
            options={
                'ordering': ['status', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CardVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('voted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='api.kanbancard')),
            ],
        ),
        migrations.AddIndex(
            model_name='kanbancard',
            index=models.Index(fields=['board', 'status', 'order'], name='api_kanbanc_board_i_cd67da_idx'),
        ),
        migrations.AddIndex(
            model_name='kanbancard',
            index=models.Index(fields=['board', 'status', '-completed_at'], name='api_kanbanc_board_i_fa2f70_idx'),
        ),
        migrations.AddIndex(
            model_name='cardvote',
            index=models.Index(fields=['card', 'ip_hash'], name='api_cardvot_card_id_f9ede5_idx'),
        ),
        migrations.AddIndex(
            model_name='cardvote',
            index=models.Index(fields=['voted_at'], name='api_cardvot_voted_a_067c2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cardvote',
            unique_together={('card', 'ip_hash')},
        ),
    ]
